version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/scripts/prototools"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/.github/actions"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/scripts"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
