name: Sync checklists & check if all checkboxes are checked

env: 
  GO_VERSION: "1.20"

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited, ready_for_review]

concurrency:
  group: github-checklist-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checklistsManagement:
    if: ${{ !(github.event.action == 'edited' && github.event.pull_request.draft == true)}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache-dependency-path: .github/actions/go.sum
    - name: Check relevant checklists
      if: github.event.action != 'edited' # Don't run on edits to the PR body
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
        OWNER: ${{ github.event.repository.owner.login }}
        REPO: ${{ github.event.repository.name }}
      run: cd ./.github/actions/add-relevant-checklists && go run main.go 
    - name: Check if all checkboxes are checked
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
        OWNER: ${{ github.event.repository.owner.login }}
        REPO: ${{ github.event.repository.name }}
      run: cd ./.github/actions/test-other && go run main.go 

