name: Sync checklists & check if all checkboxes are checked

env: 
  GO_VERSION: "1.20"

on:
  issue_comment:    
    types: [ created, edited, deleted ]
  pull_request:
    types: [ opened, synchronize, reopened, edited, ready_for_review ]


concurrency:
  group: github-checklist-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checklistsManagement:
    if: ${{ !((github.event_name == 'pull_request' && github.event.action == 'edited' && github.event.pull_request.draft) || (github.event_name == 'issue_comment' && !github.event.issue.pull_request) )}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Checkout Pull Request 
      if: github.event_name == 'issue_comment'
      run: hub pr checkout ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
         go-version: ${{ env.GO_VERSION }}
         cache-dependency-path: .github/actions/go.sum

    - name: Sync relevant checklists 
      if: ${{!( github.event.action == 'edited' || github.event_name == 'issue_comment' )}}  # Don't run on edits to the PR body
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
        OWNER: ${{ github.event.repository.owner.login }}
        REPO: ${{ github.event.repository.name }}
      run: cd ./.github/actions/add-relevant-checklists && go run main.go 

    - name: "Create a check run"
      uses: actions/github-script@v6
      with:
        script: |
          // any JavaScript code can go here, you can use Node JS APIs too.
          // Docs: https://docs.github.com/en/rest/checks/runs#create-a-check-run
          // Rest: https://octokit.github.io/rest.js/v18#checks-create
          await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head_sha: context.sha,
            name: "my-check-name",
            status: "completed",
            // Careful, code injection can happen.
            conclusion: "failure",
            // This is safe, not string interpolation.
            details_url: process.env.parameter_url,
            output: {
              title: "my check title",
              summary: "my *check* summary",
              text: "my text",
            },
          });

    - name: Ensure that all checklists are completed
      if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.draft)}} 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event_name == 'issue_comment' && github.event.issue.number || github.event.number }}
        OWNER: ${{ github.event.repository.owner.login }}
        REPO: ${{ github.event.repository.name }}
      run: cd ./.github/actions/check-if-all-checkboxes-are-checked && go run main.go 

   