name: Add relevant checklists

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  cheklists:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
         go-version: 'stable'
         cache-dependency-path: .github/actions/go.sum
    - name: Run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
        OWNER: ${{ github.event.repository.owner.login }}
        REPO: ${{ github.event.repository.name }}
      run: go run ./.github/actions/add-relevant-checklists/main.go 
