name: Build and test Go

on:
  pull_request:
    types: 
      - opened
      - synchronize
    paths:
      - '.github/go/**'
      - '.github/workflows/comment_go.yml'
      - '.github/template/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout le code
      uses: actions/checkout@v3
    - name: Setup GO
      uses: actions/setup-go@v4
      with:
         go-version: 'stable'
         cache-dependency-path: .github/go/go.sum
    - name: "Build"
      run: cd ./.github/go/ && go build -v
    - name: "Test"
      run: cd ./.github/go/ && go test -v *.go

  
    


        
        