name: Build and test Go github actions
env:
  GO_VERSION: 1.20

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - '.github/actions/**'
      - '.github/templates/**'
      - '.github/workflows/add-relevant-checklists.yml'
      - '.github/workflows/build-test-go-github-actions.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout le code
      uses: actions/checkout@v3
    - name: Setup GO
      uses: actions/setup-go@v4
      with:
         go-version: ${{ env.GO_VERSION }}
         cache-dependency-path: .github/actions/go.sum
    - name: "work"
      run: set GOWORK=$PWD/go.work
    - name: "fefds"
      run: go env
    - name: "Build"
      run: cd ./.github/actions && go build -v ./...
    - name: "Test"
      run: go test -v ./.github/actions/...