name: Build and test Go github actions

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - '.github/actions/**'
      - '.github/templates/**'
      - '.github/workflows/add-relevant-checklists.yml'
      - '.github/workflows/build-test-go-github-actions.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Setup GO
      uses: actions/setup-go@v4
      with:
         go-version: 'stable'
         cache-dependency-path: .github/actions/go.sum
    - name: "Build"
      run: go build -v ./.github/actions/...
    - name: "Test"
      run: go test -v ./.github/actions/...