name: Ajouter un commentaire à la Pull Request en Go

on:
  pull_request:
    types: 
      - opened
      - synchronize

permissions:
  contents: 'read'
  issues: 'write'
  id-token: 'write'
  pull-requests: 'write'

jobs:
  add_comment_go:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout le code
      uses: actions/checkout@v3
    - name: Ajouter un commentaire en GO
      uses: actions/setup-go@v4
      with:
         go-version: 'stable'
         cache-dependency-path: .github/go/go.sum
    - name: "go run"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
        OWNER: ${{ github.event.repository.owner.login }}
        REPO: ${{ github.event.repository.name }}
        PR_BODY : ${{ github.event.pull_request.body }}
      run: cd ./.github/go/ && go run hello.go 


        
        