name: Add relevant checklist

on:
  pull_request:
    types: 
      - opened
      - synchronize

jobs:
  add_relevent_checklist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout le code
      uses: actions/checkout@v3
    - name: Setup GO
      uses: actions/setup-go@v4
      with:
         go-version: 'stable'
         cache-dependency-path: .github/go/go.sum
    - name: "go run"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
        OWNER: ${{ github.event.repository.owner.login }}
        REPO: ${{ github.event.repository.name }}
        TEST: ${{ steps.test.outputs.CHEKLIST }}
      run: cd ./.github/go/ && go run hello.go 

  
    


        
        