name: Listen fed

on:
    check_suite:
        types: [completed]

jobs:
    listen:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout the code
          uses: actions/checkout@v3
        - name: here
          env: 
            GITHUB_REF: ${{ github.event.check_suite.head_branch }}
            CECKNAME: ${{ github.event.check_suite.app.name }}
          run : |
            echo " : $GITHUB_REF\n $CECKNAME" 