name: ReRun the check for build 

env: 
  GO_VERSION: "1.20"

on:
  issue_comment:
    types: [ created ]

concurrency:
  group: github-rerun-deploypr-${{ github.event.comment.id }}
  cancel-in-progress: true

jobs:
  rerun-checklists-management-github-action:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
         go-version: ${{ env.GO_VERSION }}
         cache-dependency-path: .github/actions/go.sum

    - name: ReRun the check for build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.issue.number }}
        OWNER: ${{ github.event.repository.owner.login }}
        REPO: ${{ github.event.repository.name }}
        JOB_TO_RERUN: build
      run: cd ./.github/actions/rerun-job && go run main.go