name: ReRun checklistManagement checkRun in the pull request of the comment

env: 
  GO_VERSION: "1.20"

on:
  issue_comment:
    types: [ created, edited, deleted ]

concurrency:
  group: github-rerun-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rerun-checklist-management-github-action:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'Breaking changes detected to `proto` files:') && (contains(github.event.comment.body, '[ ]') || contains(github.event.comment.body, '[x]'))
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the codeh
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
         go-version: ${{ env.GO_VERSION }}
         cache-dependency-path: .github/actions/go.sum
    - name: ReRun the checklistManagementsedfecfd checkRun in the pull request  frefre
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.issue.number }}
        OWNER: ${{ github.event.repository.owner.login }}
        REPO: ${{ github.event.repository.name }}
        JOB_TO_RERUN: checklistsManagement
      run: cd ./.github/actions/rerun-job && go run main.go