name: ReRun the check for successful deploy-pr checkRun in the pull request of the comment

env: 
  GO_VERSION: "1.20"

on:
  issue_comment:
    types: [ created ]

concurrency:
  group: github-rerun-deploypr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rerun-checklists-management-github-action:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
         go-version: ${{ env.GO_VERSION }}
         cache-dependency-path: .github/actions/go.sum
    - name: ReRun the check for successful deploy-pr checkRun in the pull request d
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REF: ${{ github.ref }}
        OWNER: ${{ github.event.repository.owner.login }}
        REPO: ${{ github.event.repository.name }}
        JOB_TO_RERUN: build
      run: |
        ./.github/actions/scripts/rerun-job.sh