name: Test pr review

on: 
  pull_request_review

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: "test"
      run: |
        echo "test ${{ github.event }}"