name: Test ISSUE PR

on: 
  pull_request_review_comment
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: "test"
      run: |
        echo "test ${{ github.event.comment.body }}"