name: Test

on:
  issue_comment 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the codeh
      uses: actions/checkout@v3
    - name: "test"
      run: |
        echo "test ${{ github.event.comment.body }}"