name: Add a comment

env: 
  GO_VERSION: "1.20"


on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number'
        required: true


jobs:
  transmit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the codeh
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
         go-version: ${{ env.GO_VERSION }}
         cache-dependency-path: .github/actions/go.sum
    - name: Transmit event to another workflow 
      if: github.actor == 'github-sebastien-gineste'
      env:
        TEST : "test"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.inputs.pr_number }}
        OWNER: ${{ github.event.repository.owner.login }}
        REPO: ${{ github.event.repository.name }}
      run: cd ./.github/actions/transmit-event-to-pull-request && go run main.go 