name: Transmit event to another workflow

env: 
  GO_VERSION: "1.20"

on:
  issue_comment:
    types: [ created, edited, deleted ]

jobs:
  transmit:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'Breaking changes detected to `proto` files:') && (contains(github.event.comment.body, '[ ]') || contains(github.event.comment.body, '[x]'))
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the codeh
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
         go-version: ${{ env.GO_VERSION }}
         cache-dependency-path: .github/actions/go.sum
    - name: Transmit event to another workflow 
      if: github.actor == 'github-sebastien-gineste'
      env:
        TEST : "notest"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.issue.number }}
        OWNER: ${{ github.event.repository.owner.login }}
        REPO: ${{ github.event.repository.name }}
      run: cd ./.github/actions/transmit-event-to-pull-request && go run main.go 